// products.js - আপনার পণ্যের ডেটা
// দয়া করে এই ফাইল আপডেট করলে ID গুলো ইউনিক রাখুন

const products = [
  {
    id: 1,
    name: "প্রিমিয়াম কটন শার্ট",
    category: "pant",
    subcategory: "shirt",
    price: 1200,
    originalPrice: 1500,
    discount: 20,
    rating: 4.5,
    reviews: 145,
    description: "আরামদায়ক এবং টেকসই কটন ফেব্রিক দিয়ে তৈরি প্রিমিয়াম শার্ট। নীল, সাদা এবং কালো রঙে উপলব্ধ।",
    size: "S, M, L, XL, XXL",
    color: "নীল",
    stock: 50,
    image: "https://via.placeholder.com/300x300?text=Premium+Cotton+Shirt&bg=1E90FF&color=fff"
  },
  {
    id: 2,
    name: "ঐতিহ্যবাহী জর্জেট শাড়ি",
    category: "saree",
    subcategory: "saree",
    price: 2500,
    originalPrice: 3500,
    discount: 29,
    rating: 4.8,
    reviews: 234,
    description: "হাতে বোনা জর্জেট শাড়ি, দীপাবলি এবং বিবাহের জন্য আদর্শ।",
    size: "5.5 মিটার",
    color: "লাল",
    stock: 25,
    image: "https://via.placeholder.com/300x300?text=Traditional+Saree&bg=DC143C&color=fff"
  },
  {
    id: 3,
    name: "বহুরঙী খেলনা সেট",
    category: "baby_toys",
    subcategory: "toys",
    price: 800,
    originalPrice: 950,
    discount: 16,
    rating: 4.6,
    reviews: 189,
    description: "শিশুদের জন্য নিরাপদ এবং শিক্ষামূলক খেলনা। ৬ মাস থেকে ৩ বছর বয়সী শিশুদের জন্য উপযুক্ত।",
    ageRange: "6 মাস - 3 বছর",
    material: "প্লাস্টিক, ফেব্রিক",
    stock: 40,
    image: "https://via.placeholder.com/300x300?text=Colorful+Toy+Set&bg=FFD700&color=000"
  },
  {
    id: 4,
    name: "বিশুদ্ধ জৈব মধু ৫০০ গ্রাম",
    category: "honey",
    subcategory: "organic_food",
    price: 450,
    originalPrice: 500,
    discount: 10,
    rating: 4.7,
    reviews: 312,
    description: "সম্পূর্ণ প্রাকৃতিক এবং পরিশোধিত জৈব মধু। কোনো কৃত্রিম যোজন নেই।",
    weight: "500 গ্রাম",
    source: "পার্বত্য চট্টগ্রাম",
    expiry: "২ বছর",
    stock: 60,
    image: "https://via.placeholder.com/300x300?text=Organic+Honey&bg=FFA500&color=fff"
  },
  {
    id: 5,
    name: "ওয়্যারলেস ব্লুটুথ হেডফোন",
    category: "headphones",
    subcategory: "electronics",
    price: 2000,
    originalPrice: 2800,
    discount: 29,
    rating: 4.4,
    reviews: 456,
    description: "শক্তিশালী বেস এবং পরিষ্কার সাউন্ড কোয়ালিটি সহ ওয়্যারলেস হেডফোন। ৩০ ঘন্টা ব্যাটারি লাইফ।",
    battery: "30 ঘন্টা",
    color: "কালো",
    warranty: "১ বছর",
    stock: 35,
    image: "https://via.placeholder.com/300x300?text=Wireless+Headphones&bg=000000&color=fff"
  },
  {
    id: 6,
    name: "ক্লাসিক ব্লেক লেদার জুতা",
    category: "shoes",
    subcategory: "shoes",
    price: 1500,
    originalPrice: 1800,
    discount: 17,
    rating: 4.5,
    reviews: 267,
    description: "কর্মক্ষেত্রের জন্য আদর্শ চামড়ার জুতা। আরামদায়ক এবং দীর্ঘস্থায়ী সোল।",
    size: "৬-১১",
    material: "খাঁটি চামড়া",
    stock: 45,
    image: "https://via.placeholder.com/300x300?text=Classic+Shoes&bg=1C1C1C&color=fff"
  },
  {
    id: 7,
    name: "প্রাকৃতিক ফেস ক্রিম",
    category: "cosmetics",
    subcategory: "natural_product",
    price: 600,
    originalPrice: 750,
    discount: 20,
    rating: 4.6,
    reviews: 389,
    description: "১০০% প্রাকৃতিক উপাদান দিয়ে তৈরি ফেস ক্রিম। ত্বকের আর্দ্রতা বৃদ্ধি করে এবং বার্ধক্য রোধ করে।",
    weight: "100 মিলি",
    skinType: "সব ধরনের ত্বক",
    expiry: "৩ বছর",
    stock: 70,
    image: "https://via.placeholder.com/300x300?text=Face+Cream&bg=FFB6C1&color=000"
  },
  {
    id: 8,
    name: "শিশুর মসলিন পোশাক সেট",
    category: "baby_clothes",
    subcategory: "baby_clothes",
    price: 500,
    originalPrice: 650,
    discount: 23,
    rating: 4.3,
    reviews: 156,
    description: "নরম এবং হালকা মসলিন ফেব্রিকের শিশু পোশাক সেট। ৩ মাস থেকে ১ বছর বয়সী শিশুদের জন্য।",
    ageRange: "3 মাস - 1 বছর",
    material: "মসলিন",
    quantity: "৩ পিস",
    stock: 55,
    image: "https://via.placeholder.com/300x300?text=Baby+Clothes&bg=87CEEB&color=fff"
  }
];

// expose globally to ensure renderer finds it
window.products = products;
