const products = [
    {
        id: 1,
        name: "প্রিমিয়াম কটন শার্ট",
        category: "pant",
        subcategory: "shirt",
        price: 1200,
        originalPrice: 1500,
        discount: 20,
        rating: 4.5,
        reviews: 145,
        description: "আরামদায়ক এবং টেকসই কটন ফেব্রিক দিয়ে তৈরি প্রিমিয়াম শার্ট। নীল, সাদা এবং কালো রঙে উপলব্ধ।",
        size: "S, M, L, XL, XXL",
        color: "নীল",
        stock: 50,
        image: "https://via.placeholder.com/300x300?text=Premium+Cotton+Shirt&bg=1E90FF&color=fff"
    },
    {
        id: 2,
        name: "ঐতিহ্যবাহী জর্জেট শাড়ি",
        category: "saree",
        subcategory: "saree",
        price: 2500,
        originalPrice: 3500,
        discount: 29,
        rating: 4.8,
        reviews: 234,
        description: "হাতে বোনা জর্জেট শাড়ি, দীপাবলি এবং বিবাহের জন্য আদর্শ। সোনালি এবং রূপালি কাজ সহ।",
        size: "5.5 মিটার",
        color: "লাল",
        stock: 25,
        image: "https://via.placeholder.com/300x300?text=Traditional+Saree&bg=DC143C&color=fff"
    },
    {
        id: 3,
        name: "বহুরঙী খেলনা সেট",
        category: "baby_toys",
        subcategory: "toys",
        price: 800,
        originalPrice: 950,
        discount: 16,
        rating: 4.6,
        reviews: 189,
        description: "শিশুদের জন্য নিরাপদ এবং শিক্ষামূলক খেলনা। ৬ মাস থেকে ৩ বছর বয়সী শিশুদের জন্য উপযুক্ত।",
        ageRange: "6 মাস - 3 বছর",
        material: "প্লাস্টিক, ফেব্রিক",
        stock: 40,
        image: "https://via.placeholder.com/300x300?text=Colorful+Toy+Set&bg=FFD700&color=000"
    },
    {
        id: 4,
        name: "বিশুদ্ধ জৈব মধু ৫০০ গ্রাম",
        category: "honey",
        subcategory: "organic_food",
        price: 450,
        originalPrice: 500,
        discount: 10,
        rating: 4.7,
        reviews: 312,
        description: "সম্পূর্ণ প্রাকৃতিক এবং পরিশোধিত জৈব মধু। কোনো কৃত্রিম যোজন নেই।",
        weight: "500 গ্রাম",
        source: "পার্বত্য চট্টগ্রাম",
        expiry: "২ বছর",
        stock: 60,
        image: "https://via.placeholder.com/300x300?text=Organic+Honey&bg=FFA500&color=fff"
    },
    {
        id: 5,
        name: "ওয়্যারলেস ব্লুটুথ হেডফোন",
        category: "headphones",
        subcategory: "electronics",
        price: 2000,
        originalPrice: 2800,
        discount: 29,
        rating: 4.4,
        reviews: 456,
        description: "শক্তিশালী বেস এবং পরিষ্কার সাউন্ড কোয়ালিটি সহ ওয়্যারলেস হেডফোন। ৩০ ঘন্টা ব্যাটারি লাইফ।",
        battery: "30 ঘন্টা",
        color: "কালো",
        warranty: "১ বছর",
        stock: 35,
        image: "https://via.placeholder.com/300x300?text=Wireless+Headphones&bg=000000&color=fff"
    },
    {
        id: 6,
        name: "ক্লাসিক ব্লেক লেদার জুতা",
        category: "shoes",
        subcategory: "shoes",
        price: 1500,
        originalPrice: 1800,
        discount: 17,
        rating: 4.5,
        reviews: 267,
        description: "কর্মক্ষেত্রের জন্য আদর্শ চামড়ার জুতা। আরামদায়ক এবং দীর্ঘস্থায়ী সোল।",
        size: "৬-১১",
        material: "খাঁটি চামড়া",
        stock: 45,
        image: "https://via.placeholder.com/300x300?text=Classic+Shoes&bg=1C1C1C&color=fff"
    },
    {
        id: 7,
        name: "প্রাকৃতিক ফেস ক্রিম",
        category: "cosmetics",
        subcategory: "natural_product",
        price: 600,
        originalPrice: 750,
        discount: 20,
        rating: 4.6,
        reviews: 389,
        description: "১০০% প্রাকৃতিক উপাদান দিয়ে তৈরি ফেস ক্রিম। ত্বকের আর্দ্রতা বৃদ্ধি করে এবং বার্ধক্য রোধ করে।",
        weight: "100 মিলি",
        skinType: "সব ধরনের ত্বক",
        expiry: "৩ বছর",
        stock: 70,
        image: "https://via.placeholder.com/300x300?text=Face+Cream&bg=FFB6C1&color=000"
    },
    {
        id: 8,
        name: "শিশুর মসলিন পোশাক সেট",
        category: "baby_clothes",
        subcategory: "baby_clothes",
        price: 500,
        originalPrice: 650,
        discount: 23,
        rating: 4.3,
        reviews: 156,
        description: "নরম এবং হালকা মসলিন ফেব্রিকের শিশু পোশাক সেট। ৩ মাস থেকে ১ বছর বয়সী শিশুদের জন্য।",
        ageRange: "3 মাস - 1 বছর",
        material: "মসলিন",
        quantity: "৩ পিস",
        stock: 55,
        image: "https://via.placeholder.com/300x300?text=Baby+Clothes&bg=87CEEB&color=fff"
    },
    {
        id: 9,
        name: "ফর্মাল কালো প্যান্ট",
        category: "pant",
        subcategory: "pant",
        price: 1800,
        originalPrice: 2200,
        discount: 18,
        rating: 4.5,
        reviews: 223,
        description: "অফিসের জন্য পারফেক্ট ফর্মাল প্যান্ট। স্ট্রেচ ফেব্রিক এবং আধুনিক ডিজাইন।",
        size: "28-40",
        material: "পলিয়েস্টার + কটন",
        stock: 48,
        image: "https://via.placeholder.com/300x300?text=Formal+Pants&bg=2F4F4F&color=fff"
    },
    {
        id: 10,
        name: "রঙিন কুর্তি কালেকশন",
        category: "kurti",
        subcategory: "women_fashion",
        price: 950,
        originalPrice: 1200,
        discount: 21,
        rating: 4.7,
        reviews: 198,
        description: "ঐতিহ্যবাহী এবং আধুনিক ডিজাইনের সমন্বয়ে তৈরি কুর্তি। পার্টি এবং দৈনন্দিন পরিধানের জন্য উপযুক্ত।",
        size: "XS-XL",
        color: "গোলাপি",
        material: "রেয়ন",
        stock: 52,
        image: "https://via.placeholder.com/300x300?text=Colorful+Kurti&bg=FF69B4&color=fff"
    },
    {
        id: 11,
        name: "দ্রুত চার্জিং মোবাইল চার্জার",
        category: "charger",
        subcategory: "electronics",
        price: 400,
        originalPrice: 550,
        discount: 27,
        rating: 4.3,
        reviews: 578,
        description: "৬৫ ওয়াট দ্রুত চার্জিং প্রযুক্তি সহ মোবাইল চার্জার। সব ব্র্যান্ডের ফোনের জন্য কম্প্যাটিবল।",
        wattage: "65W",
        ports: "USB-C",
        warranty: "১.৫ বছর",
        stock: 80,
        image: "https://via.placeholder.com/300x300?text=Fast+Charger&bg=32CD32&color=fff"
    },
    {
        id: 12,
        name: "ক্যাজুয়াল টি-শার্ট কালেকশন",
        category: "t-shirt",
        subcategory: "t-shirt",
        price: 550,
        originalPrice: 800,
        discount: 31,
        rating: 4.4,
        reviews: 445,
        description: "আরামদায়ক এবং ঢিলাঢালা ফিটের ক্যাজুয়াল টি-শার্ট। বিভিন্ন রঙে পাওয়া যায়।",
        size: "S-XXL",
        material: "১০০% কটন",
        colors: ["কালো", "সাদা", "নীল", "লাল"],
        stock: 92,
        image: "https://via.placeholder.com/300x300?text=T-Shirt&bg=4169E1&color=fff"
    },
    {
        id: 13,
        name: "অর্��ানিক গ্রিন টি প্যাকেট",
        category: "tea",
        subcategory: "natural_product",
        price: 350,
        originalPrice: 400,
        discount: 13,
        rating: 4.5,
        reviews: 267,
        description: "স্বাস্থ্যকর এবং সুস্বাদু জৈব গ্রিন টি। স্ট্রেস কমাতে এবং শরীরের ওজন নিয়ন্ত্রণে সহায়ক।",
        weight: "100 গ্রাম",
        teabags: "50 থলে",
        origin: "দার্জিলিং",
        stock: 65,
        image: "https://via.placeholder.com/300x300?text=Green+Tea&bg=00AA00&color=fff"
    },
    {
        id: 14,
        name: "মহিলার ক্যাজুয়াল জ্যাকেট",
        category: "jacket",
        subcategory: "women_fashion",
        price: 2200,
        originalPrice: 2800,
        discount: 21,
        rating: 4.6,
        reviews: 178,
        description: "শীতকালীন এবং ক্যাজুয়াল পরিধানের জন্য আদর্শ জ্যাকেট। জলরোধী এবং উষ্ণ।",
        size: "XS-L",
        material: "পলিয়েস্টার",
        color: "কালো",
        stock: 38,
        image: "https://via.placeholder.com/300x300?text=Womens+Jacket&bg=696969&color=fff"
    },
    {
        id: 15,
        name: "শিশুর কমফোর্ট জুতা",
        category: "baby_shoes",
        subcategory: "baby_shoes",
        price: 600,
        originalPrice: 750,
        discount: 20,
        rating: 4.5,
        reviews: 189,
        description: "নরম এবং আরামদায়ক শিশু জুতা। পায়ের বৃদ্ধির সাথে খাপ খায়।",
        ageRange: "৬ মাস - ২ বছর",
        size: "3-6",
        material: "ফেব্রিক + রাবার",
        stock: 42,
        image: "https://via.placeholder.com/300x300?text=Baby+Shoes&bg=FF6347&color=fff"
    },
    {
        id: 16,
        name: "স্মার্টফোন প্রটেক্টিভ কেস",
        category: "accessories",
        subcategory: "electronics",
        price: 350,
        originalPrice: 450,
        discount: 22,
        rating: 4.4,
        reviews: 612,
        description: "ড্রপ রেজিস্ট্যান্ট এবং ডিউরেবল স্মার্টফোন কেস। সব জনপ্রিয় ব্র্যান্ডের জন্য উপলব্ধ।",
        compatibility: "iPhone & Android",
        material: "সিলিকন",
        colors: ["কালো", "নীল", "লাল"],
        stock: 105,
        image: "https://via.placeholder.com/300x300?text=Phone+Case&bg=9370DB&color=fff"
    }
];
